@backend = https://app-backend-kmbbn7u24cfd2.azurewebsites.net
###


###
POST {{backend}}/ask HTTP/1.1
content-type: application/json

{
    "approach": "rtr", 
    "question": "デュアルインバータシステムの特徴を教えてください"
}

###
POST {{backend}}/ask HTTP/1.1
content-type: application/json

{
    "approach": "rtr", 
    "question": "従来のインバーターシステムの課題を教えてください"
}


###
API Managementの動作確認
###

@apimanagement = https://apim-kmbbn7u24cfd2.azure-api.net
###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json

{
    "approach": "rtr", 
    "question": "デュアルインバータシステムの特徴を教えてください"
}



###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: xxxx

{
    "approach": "rtr", 
    "question": "デュアルインバータシステムの特徴を教えてください"
}
