@backend = https://app-backend-xxx.azurewebsites.net
###


###
POST {{backend}}/ask HTTP/1.1
content-type: application/json

{
    "approach": "rtr", 
    "question": "EVとBEVの違いはなんですか"
}

###
POST {{backend}}/ask HTTP/1.1
content-type: application/json

{
    "approach": "rtr", 
    "question": "デュアルインバータシステムの特徴を教えてください"
}


###
API Managementの動作確認
###

@apimanagement = https://apim-xxx.azure-api.net
###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json

{
    "approach": "rtr", 
    "question": "EVとBEVの違いはなんですか"
}



###
POST {{apimanagement}}/api/ask HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: xxxx

{
    "approach": "rtr", 
    "question": "EVとBEVの違いはなんですか"
}
